---
title: Knowledge Quiz Test
hero_image: images/banner.png
description: Quizzy Content
meta_title: Knowledge Quiz Meta Title
meta_description: Knowledge Quiz Meta Description
version: 0.1
listed: false
copyedit: false
last_tested: 2018-10-12
steps:
- title: Introduction
- title: Test Your Knowledge
  knowledge_quiz:
    path: quiz1
    version: 6
    questions: 5
    passing_score: 4
  completion:
  - engaged
  - internal
- title: Reflection
  quiz: true
- title: What next?
  completion:
  - external
