name: GitHub Actions Test
on:
  push:
    branches:
      - actions-test-plus-action
jobs:
  Sync-image-to-S3:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
      AWS_BUCKET: learning-resources-dev-staging
    steps:
      - name: Setup AWS CLI
        uses: unfor19/install-aws-cli-action@v1
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload content directories
        uses: ./
        id: upload_directories
        with:
          filter: code,data,images,dist,.github,.git
      - name: Show the directories
        run: echo "Directories uploaded were ${{ steps.upload_directories.outputs.directories }}"
