name: GitHub Actions Test
on:
  push:
    branches:
      - actions-test
jobs:
  Sync-image-to-S3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [images, resources, solutions]
    steps:
      # - name: Dump-github-context
      #   run: echo "$GITHUB_CONTEXT"
      #   shell: bash
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: actions/checkout@v2
      # - uses: keithweaver/aws-s3-github-action@v1.0.0
      #   with:
      #     command: cp
      #     source: ./en/${{ matrix.directory }}/
      #     # ${{ github.event.repository.name }} is unavailable in scheduled actions!
      #     destination: s3://learning-resources-dev-staging/projects/${{ github.event.repository.name }}/${{ github.sha }}/en/${{ matrix.directory }}/
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws_region: eu-west-2
      #     flags: --recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./en/${{ matrix.directory }}/ s3://learning-resources-dev-staging/projects/${{ github.event.repository.name }}/${{ github.sha }}/en/${{ matrix.directory }} --delete
