name: GitHub Actions Test
on:
  push:
    branches:
      - actions-test
jobs:
  Sync-image-to-S3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [images, resources, solutions]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Deploy static assets to S3 bucket
        run: aws s3 sync ./en/${{ matrix.directory }}/ s3://learning-resources-dev-staging/projects/${{ github.event.repository.name }}/${{ github.sha }}/en/${{ matrix.directory }} --delete
